#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "custom_door_a/geo.inc.c"
#include "custom_door_b/geo.inc.c"
#include "custom_portal_w/geo.inc.c"
#include "animated_wall_catA/geo.inc.c"
#include "animated_wall_catB/geo.inc.c"
#include "animated_wall_birdA/geo.inc.c"
#include "animated_wall_birdB/geo.inc.c"
#include "animated_wall_dinoA/geo.inc.c"
#include "animated_wall_dinoB/geo.inc.c"
#include "animated_wall_dogA/geo.inc.c"
#include "animated_wall_dogB/geo.inc.c"
#include "crystal_projectile/geo.inc.c"
#include "despair/geo.inc.c"
#include "custom_door_c/geo.inc.c"
#include "custom_secret/geo.inc.c"
#include "animated_wall_alienA/geo.inc.c"
#include "animated_wall_alienB/geo.inc.c"
#include "custom_boss_portal/geo.inc.c"