extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_macro_objs[];
extern u8 bitdw_dl_carpet_i8[];
extern u8 bitdw_dl_crystal_grey_ci8[];
extern u8 bitdw_dl_crystal_grey_ci8_pal_rgba16[];
extern u8 bitdw_dl_crystal_pink_ci8[];
extern u8 bitdw_dl_crystal_pink_ci8_pal_rgba16[];
extern u8 bitdw_dl_Glass_2_ia8[];
extern u8 bitdw_dl_blind_texture_i8[];
extern Vtx bitdw_dl_A_Arena_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_A_Arena_mesh_layer_1_vtx_0[240];
extern Gfx bitdw_dl_A_Arena_mesh_layer_1_tri_0[];
extern Vtx bitdw_dl_A_Arena_mesh_layer_1_vtx_1[264];
extern Gfx bitdw_dl_A_Arena_mesh_layer_1_tri_1[];
extern Vtx bitdw_dl_A_Arena_mesh_layer_1_vtx_2[282];
extern Gfx bitdw_dl_A_Arena_mesh_layer_1_tri_2[];
extern Vtx bitdw_dl_A_Arena_mesh_layer_5_vtx_cull[8];
extern Vtx bitdw_dl_A_Arena_mesh_layer_5_vtx_0[96];
extern Gfx bitdw_dl_A_Arena_mesh_layer_5_tri_0[];
extern Vtx bitdw_dl_B_Elise_mesh_layer_5_vtx_cull[8];
extern Vtx bitdw_dl_B_Elise_mesh_layer_5_vtx_0[44];
extern Gfx bitdw_dl_B_Elise_mesh_layer_5_tri_0[];
extern Vtx bitdw_dl_B_Elise_mesh_layer_1_vtx_cull[8];
extern Vtx bitdw_dl_B_Elise_mesh_layer_1_vtx_0[720];
extern Gfx bitdw_dl_B_Elise_mesh_layer_1_tri_0[];
extern Vtx bitdw_dl_B_Elise_mesh_layer_1_vtx_1[112];
extern Gfx bitdw_dl_B_Elise_mesh_layer_1_tri_1[];
extern Gfx mat_bitdw_dl_rock[];
extern Gfx mat_revert_bitdw_dl_rock[];
extern Gfx mat_bitdw_dl_Crystal_side[];
extern Gfx mat_revert_bitdw_dl_Crystal_side[];
extern Gfx mat_bitdw_dl_Crystal_pink[];
extern Gfx mat_revert_bitdw_dl_Crystal_pink[];
extern Gfx mat_bitdw_dl_Glass[];
extern Gfx mat_revert_bitdw_dl_Glass[];
extern Gfx mat_bitdw_dl_White[];
extern Gfx mat_revert_bitdw_dl_White[];
extern Gfx mat_bitdw_dl_Blank[];
extern Gfx mat_revert_bitdw_dl_Blank[];
extern Gfx bitdw_dl_A_Arena_mesh_layer_1[];
extern Gfx bitdw_dl_A_Arena_mesh_layer_5[];
extern Gfx bitdw_dl_B_Elise_mesh_layer_5[];
extern Gfx bitdw_dl_B_Elise_mesh_layer_1[];
extern Gfx bitdw_dl_material_revert_render_settings[];
