extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern u8 castle_inside_dl_crystal_rgba16[];
extern u8 castle_inside_dl_Glass_2_ia4[];
extern u8 castle_inside_dl_blind_texture_i8[];
extern Vtx castle_inside_dl_Crystal_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Crystal_mesh_layer_1_vtx_0[76];
extern Gfx castle_inside_dl_Crystal_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Crystal_mesh_layer_5_vtx_cull[8];
extern Vtx castle_inside_dl_Crystal_mesh_layer_5_vtx_0[76];
extern Gfx castle_inside_dl_Crystal_mesh_layer_5_tri_0[];
extern Vtx castle_inside_dl_Crystal_mesh_layer_5_vtx_1[49];
extern Gfx castle_inside_dl_Crystal_mesh_layer_5_tri_1[];
extern Vtx castle_inside_dl_Portal_000_mesh_layer_5_vtx_cull[8];
extern Vtx castle_inside_dl_Portal_000_mesh_layer_5_vtx_0[22];
extern Gfx castle_inside_dl_Portal_000_mesh_layer_5_tri_0[];
extern Vtx castle_inside_dl_Portal_001_mesh_layer_5_vtx_cull[8];
extern Vtx castle_inside_dl_Portal_001_mesh_layer_5_vtx_0[22];
extern Gfx castle_inside_dl_Portal_001_mesh_layer_5_tri_0[];
extern Vtx castle_inside_dl_Portal_002_mesh_layer_5_vtx_cull[8];
extern Vtx castle_inside_dl_Portal_002_mesh_layer_5_vtx_0[22];
extern Gfx castle_inside_dl_Portal_002_mesh_layer_5_tri_0[];
extern Gfx mat_castle_inside_dl_Crystaline[];
extern Gfx mat_revert_castle_inside_dl_Crystaline[];
extern Gfx mat_castle_inside_dl_Glass[];
extern Gfx mat_revert_castle_inside_dl_Glass[];
extern Gfx mat_castle_inside_dl_White[];
extern Gfx mat_revert_castle_inside_dl_White[];
extern Gfx castle_inside_dl_Crystal_mesh_layer_1[];
extern Gfx castle_inside_dl_Crystal_mesh_layer_5[];
extern Gfx castle_inside_dl_Portal_000_mesh_layer_5[];
extern Gfx castle_inside_dl_Portal_001_mesh_layer_5[];
extern Gfx castle_inside_dl_Portal_002_mesh_layer_5[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
